Update autolinker 3 15 0
meganz/Autolinker.js pull request #1
Opened 2022-08-01 22:31 UTC by bfMega

2022-08-02 13:02 UTC, diegocr requested changes
Thanks Ben!

Under https://github.com/meganz/Autolinker.js/commit/e63dd8c0016e503e17b05f08ff97c2ba5417bf1f i took the chance to switch the build procedure to generate ES2018-compliant files instead.

Would you mind adding into `scripts/build.ts` a function that programmatically changes the UTF-8 characters, as a mean to ease further maintenance / upgrades in the long run, please? If you do find any trouble with this just sync the changes and apply manually, tho.

2022-08-03 01:50 UTC, bfMega commented
Removed some of the problematic characters in the rest of the code + Updated the tldRegex generating script to replace the UTF-8 characters. Also changed the rollup config to match the filename we use.

2022-08-05 12:42 UTC, diegocr commented on scripts/update-tld-regex.ts
> +    const matches = tldRegex.match(/[\u0100-\uFFFF]/g) || [];
```suggestion
    const matches = tldRegex.match(/[\u007F-\uFFFF]/g) || [];
```

2022-08-05 12:42 UTC, diegocr commented on scripts/update-tld-regex.ts
> +        }
```suggestion
        const codePoint = (match.codePointAt(0) | 0).toString(16).padStart(4, '0');
```

2022-08-05 12:46 UTC, diegocr commented
Overall looks good, will take care myself from there, thanks!

2022-08-05 12:46 UTC, diegocr approved these changes

2022-08-05 12:47 UTC, merged